version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  
  web: 
    build: ../backend
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi
    volumes:
      - static_value:/app/static/
    depends_on:
      - db
    env_file:
      - ./.env

  celery:
    build: ../backend
    restart: always
    command: celery -A backend worker -B -l INFO
    depends_on:
      - web
      - redis
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - web

  redis:
    image: redis:5-alpine
    depends_on:
      - web

volumes:
  static_value:
