# Generated by Django 3.1.14 on 2022-05-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.PositiveIntegerField(verbose_name='Артикул')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отслеживаемый артикул',
                'verbose_name_plural': 'Отслеживаемые артикулы',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.PositiveIntegerField(verbose_name='Артикул')),
                ('name', models.CharField(max_length=200, verbose_name='Название рецепта')),
                ('value', models.PositiveIntegerField(verbose_name='Цена')),
                ('discont_value', models.PositiveIntegerField(verbose_name='Цена со скидкой')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания статьи')),
                ('brand', models.CharField(max_length=200, verbose_name='Бренд')),
                ('supplier', models.CharField(max_length=200, verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Карточка товара',
                'verbose_name_plural': 'Карточки товаров',
            },
        ),
    ]
