# Generated by Django 3.1.14 on 2022-05-04 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20220504_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.article', verbose_name='Артикул'),
        ),
    ]
