# Generated by Django 3.1.14 on 2022-05-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_article_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='card',
            name='discont_value',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='card',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Цена со скидкой'),
        ),
    ]
